spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto-security?useSSL=false&serverTimezone=UTC
    username: crypto-security
    password: 123456

#logging:
#  level:
#    root: DEBUG
#    com.nacrt.exchange.wallet.crypto.security: DEBUG