spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto-security?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: crypto-security
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create  # 每次启动时创建表
    show-sql: true     # 打印SQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # 显示建表SQL
        show_sql: true
        # 格式化SQL
        format_sql: true
        # 自动创建表
        generate-ddl: true
        # 显示建表SQL
        hbm2ddl:
          auto: create