server:
  port: 80
#  servlet:
#    context-path: /api/crypto-security

spring:
  main:
    allow-bean-definition-overriding: true # bean定义可覆盖
    banner-mode: off # 不打印banner
  application:
    name: crypto-security-app
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:/application.yml
      - optional:classpath:/application-${spring.profiles.active}.yml


# 日志级别
logging:
  level:
    root: INFO