spring:
  application:
    name: crypto-security-app
  profiles:
    active: dev
  config:
    import:
      - optional:classpath:/application.yml
      - optional:classpath:/application-${spring.profiles.active}.yml